spring:
  application:
    name: FreelanceRestApi
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


app:
  security:
    jwt:
      secret-key: c0182a0c93fdf659eb425445c099af10c66ce08fca923360bf67139abb1fb5a3
      expiration: 86400000 # 1 day
      refresh-token:
        expiration: 604800000 # 7 days


server:
  port: 8090